import Link from 'next/link'

export default function About() {
  return (
    <main className="min-h-screen bg-background">
      <div className="max-w-2xl mx-auto px-6 py-20 space-y-14">

        {/* ── Section 1 — Header ──────────────────────────────── */}
        <div>
          <h1 className="text-3xl font-semibold text-foreground">
            TrueCase
          </h1>
          <p className="mt-2 text-lg text-foreground-muted">
            Build business cases you can actually trust.
          </p>
        </div>

        {/* ── Section 2 — What it does ────────────────────────── */}
        <div className="space-y-5">
          <p className="text-sm text-foreground leading-relaxed">
            TrueCase is an AI-powered business case builder for AI
            investments. It generates a financial ROI projection and
            immediately asks whether the governance conditions that
            determine its reliability are actually in place.
          </p>

          <p className="text-sm text-foreground leading-relaxed">
            Most AI ROI projections fail not because the model was wrong
            — but because the governance was missing. No hard output cap.
            No human override. No documented training assumptions. The
            Ticketmaster/Oasis pricing incident, Amazon&apos;s recruitment
            tool failure, and NHS AI deterioration tool underperformance
            all share the same root cause: the projection assumed
            governance that did not exist.
          </p>

          <p className="text-sm text-foreground leading-relaxed">
            TrueCase connects governance assessment to ROI reliability in
            a single tool. The output is a one-page business case —
            downloadable as a PDF — that shows both the headline
            projection and the reliability-adjusted projection. The gap
            between them is the governance argument.
          </p>
        </div>

        {/* ── Section 3 — Who it is for ───────────────────────── */}
        <div>
          <p className="text-sm font-medium uppercase tracking-wide text-foreground-muted mb-6">
            Who it is for
          </p>

          <div className="space-y-5">

            <div className="border-l-2 border-brand pl-4">
              <p className="text-sm font-medium text-foreground mb-1">
                The internal AI PM
              </p>
              <p className="text-sm text-foreground-muted leading-relaxed">
                Seeking budget approval and needing a projection they can
                defend under governance questioning.
              </p>
            </div>

            <div className="border-l-2 border-brand pl-4">
              <p className="text-sm font-medium text-foreground mb-1">
                The startup founder
              </p>
              <p className="text-sm text-foreground-muted leading-relaxed">
                Preparing investor materials that survive due diligence
                from a governance-aware investor.
              </p>
            </div>

            <div className="border-l-2 border-brand pl-4">
              <p className="text-sm font-medium text-foreground mb-1">
                The enterprise buyer
              </p>
              <p className="text-sm text-foreground-muted leading-relaxed">
                Stress-testing a vendor&apos;s ROI claim against their
                specific governance context before signing.
              </p>
            </div>

          </div>
        </div>

        {/* ── Section 4 — How TrueCase works ─────────────────── */}
        <div>
          <p className="text-sm font-medium uppercase tracking-wide text-foreground-muted mb-6">
            How TrueCase works
          </p>

          <div className="space-y-5">
            <p className="text-sm text-foreground leading-relaxed">
              TrueCase&apos;s governance assessment is grounded in a verified
              regulatory knowledge base — six governance elements each traced
              to primary source UK legislation and official guidance. Every
              regulatory warning links to its source document so you can
              verify the claim yourself.
            </p>

            <p className="text-sm text-foreground leading-relaxed">
              The financial projection is pure arithmetic from your inputs.
              The reliability-adjusted projection is that figure multiplied
              by your governance score. The gap between them is what your
              governance gaps cost you.
            </p>

            <p className="text-sm text-foreground leading-relaxed">
              The business case narrative is generated by Claude (Anthropic),
              constrained to synthesise only from your inputs and the
              knowledge base. It cannot add claims beyond those verified
              sources.
            </p>
          </div>

          <p className="inline-block mt-6 bg-surface border border-border px-3 py-2 text-xs text-foreground-muted rounded">
            Knowledge base v1.0 — regulatory sources verified April 2026
          </p>
        </div>

        {/* ── Section 5 — Scope note ──────────────────────────────── */}
        <div className="rounded border border-border bg-surface p-5">
          <p className="text-sm text-foreground-muted leading-relaxed">
            TrueCase is designed for narrow AI systems with constrained
            output spaces — classifiers, pricing engines, recommendation
            systems, sentiment monitors. It does not apply to autonomous
            agents or open-ended generative systems.
          </p>
        </div>

        {/* ── Section 6 — Built by ────────────────────────────── */}
        <div className="space-y-3">
          <p className="text-sm text-foreground leading-relaxed">
            Built by Ogbebor Osaheni as part of a portfolio of five
            shipped AI products across UK live events, broadcast media,
            content moderation, film production, and story development.
          </p>

          <a
            href="https://aiirveon.vercel.app"
            target="_blank"
            rel="noopener noreferrer"
            className="text-sm text-brand hover:text-brand-hover transition-colors duration-150"
          >
            View the full portfolio →
          </a>
        </div>

        {/* ── Section 6 — Back to calculator ─────────────────── */}
        <div className="pt-2 border-t border-border">
          <Link
            href="/"
            className="text-sm text-foreground-muted hover:text-foreground transition-colors duration-150"
          >
            ← Back to TrueCase
          </Link>
        </div>

      </div>
    </main>
  )
}
