// No 'use client' needed — no hooks or events. Rendered inside client tree.

interface NarrativeDisplayProps {
  section1:         string
  section2:         string
  section3:         string
  isLoading:        boolean
  error:            string | null
  onDownloadPDF?:   () => void
  onExportHTML?:    () => void
  isExportingPDF?:  boolean
}

const sectionLabelClass =
  'text-xs font-medium uppercase tracking-wide text-foreground-muted mb-3'

const sectionBodyClass = 'text-sm text-foreground leading-relaxed whitespace-pre-wrap'

export default function NarrativeDisplay({
  section1,
  section2,
  section3,
  isLoading,
  error,
  onDownloadPDF,
  onExportHTML,
  isExportingPDF = false,
}: NarrativeDisplayProps) {

  // ── Loading ──────────────────────────────────────────────────────────────────
  if (isLoading) {
    return (
      <div className="rounded border border-border bg-surface p-10 text-center">
        <p className="text-sm text-foreground-muted animate-pulse">
          Building your business case...
        </p>
      </div>
    )
  }

  // ── Error ────────────────────────────────────────────────────────────────────
  if (error) {
    return (
      <div className="rounded border border-missing bg-missing-bg p-6">
        <p className="text-xs font-medium uppercase tracking-wide text-missing mb-1">
          Error
        </p>
        <p className="text-sm text-destructive">{error}</p>
      </div>
    )
  }

  // ── No content yet ───────────────────────────────────────────────────────────
  if (!section1 && !section2 && !section3) return null

  // ── Narrative content ────────────────────────────────────────────────────────
  return (
    <section className="rounded border border-border bg-surface-raised">

      {/* Grounding disclosure */}
      <div className="px-6 pt-6">
        <p className="text-xs text-foreground-muted bg-surface border border-border px-4 py-3 rounded mb-4">
          This business case will be generated by Claude (Anthropic) using your
          financial inputs and the TrueCase regulatory knowledge base (v1.0,
          verified April 2026). Financial figures are calculated from your
          inputs. Regulatory references come from the knowledge base. Claude
          does not add claims beyond these sources. TrueCase stores nothing.
        </p>
      </div>

      {/* Section 1 — Business Case Summary */}
      <div className="p-6 border-b border-border">
        <p className={sectionLabelClass}>Business Case Summary</p>
        <p className={sectionBodyClass}>{section1}</p>
      </div>

      {/* Section 2 — Governance Assessment */}
      <div className="p-6 border-b border-border">
        <p className={sectionLabelClass}>Governance Assessment</p>
        <p className={sectionBodyClass}>{section2}</p>
      </div>

      {/* Section 3 — Social Return Signal */}
      <div className="p-6 border-b border-border">
        <p className={sectionLabelClass}>Social Return Signal</p>
        <p className={sectionBodyClass}>{section3}</p>
      </div>

      {/* AI-generated label */}
      <div className="px-6 py-4 border-b border-border">
        <p className="text-xs text-foreground-subtle mt-4">
          Generated by Claude (Anthropic) from your inputs and TrueCase
          knowledge base v1.0 (verified April 2026). Financial figures are
          your inputs. Regulatory references are from the knowledge base.
        </p>
      </div>

      {/* ── Export buttons ───────────────────────────────────────────────────── */}
      <div className="p-6 space-y-4">

        {/* Disclosure — shown above export buttons */}
        <p className="text-xs text-foreground-muted">
          Generated server-side and immediately discarded.
          Nothing is stored by TrueCase.
        </p>

        {/* Button pair */}
        <div className="flex gap-3">
          <button
            type="button"
            onClick={onDownloadPDF}
            disabled={isExportingPDF}
            className="flex-1 rounded border border-brand bg-brand px-5 py-2.5
                       text-sm font-medium text-white transition-colors duration-150
                       hover:bg-brand-hover
                       disabled:cursor-not-allowed disabled:opacity-50"
          >
            {isExportingPDF ? 'Generating PDF…' : '↓ Download PDF'}
          </button>

          <button
            type="button"
            onClick={onExportHTML}
            className="flex-1 rounded border border-border bg-surface px-5 py-2.5
                       text-sm font-medium text-foreground transition-colors duration-150
                       hover:bg-surface-muted"
          >
            ↓ Export HTML Report
          </button>
        </div>

        {/* Format hint */}
        <p className="text-xs text-foreground-subtle">
          PDF for formal submissions. HTML for sharing and editing.
        </p>

      </div>

    </section>
  )
}
